name: Build

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
        features:
          - std
        include:
          - rust: nightly
            features: std,nightly
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    env:
      TOOLCHAIN: ${{ matrix.rust }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal
          components: rustfmt, clippy
      - name: Build
        run: cargo build -v --features ${{ matrix.features }}
      - name: Test
        run: cargo test -v --features ${{ matrix.features }}
      - name: Lint
        run: cargo clippy -- -D warnings
      - name: Format check
        run: cargo fmt -v -- --check
