name: Build

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
        features:
          - std
        include:
          - rust: nightly
            features: std,nightly
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust toolchain
        run: |
          rustup set profile minimal
          rustup toolchain install ${{ matrix.rust }} -c clippy,rustfmt
          rustup override set ${{ matrix.rust }}
      - name: Build
        run: cargo build -v --features ${{ matrix.features }}
      - name: Test
        run: cargo test -v --features ${{ matrix.features }}
      - name: Lint
        run: cargo clippy -- -D warnings
      - name: Format check
        run: cargo fmt -v -- --check
